service: seemy-github

frameworkVersion: '2'

useDotenv: true
plugins:
  - serverless-plugin-typescript
  - serverless-jetpack

custom:
  serverless-jetpack:
    mode: npm

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stage: production
  versionFunctions: false
  tags:
    seemyintegration: github
    seemycomponent: vcs
    service: seemy
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "sqs:SendMessage"
        Resource: 
          - Fn::GetAtt:
            - PageQueue
            - Arn
      - Effect: "Allow"
        Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:BatchWriteItem
        Resource: 
          - Fn::GetAtt:
            - pullTable
            - Arn
          - Fn::GetAtt:
            - issueTable
            - Arn

  environment:
    PAGE_QUEUE: !Ref PageQueue
    PULL_TABLE: !Select [1, !Split ['/', !GetAtt pullTable.Arn]] 
    ISSUE_TABLE: !Select [1, !Split ['/', !GetAtt issueTable.Arn]] 
    appId: ${env:appId}
    privateKey: ${env:privateKey}
    DEBUG: "*"

functions:
  pageQueueHandler:
    handler: src/inputHandler.sqsPageQueueHandler
    maximumRetryAttempts: 2
    timeout: 900
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PageQueue
              - Arn

  http:
    handler: src/inputHandler.httpQueryRepoHandler
    events:
      - httpApi:
          path: /{installationId}/{owner}/{repo}
          method: GET

package:
  exclude:
    - "tests/**"
    - "*.md"
    - "wallaby.js"
    - "jest.config.js"
    - "workspace.code-workspace/**"
    - "package-lock.json"
    - "package.json"
    - "node_modules/aws-sdk/**"
    - "coverage/**"
    - ".*"
    - ".*/**"

resources:
  Resources:

    PageQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: seemyGithubPageDLQ.fifo
        FifoQueue: true
        ContentBasedDeduplication: true

    PageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: seemyGithubPage.fifo
        VisibilityTimeout: 1200
        FifoQueue: true
        ContentBasedDeduplication: true
        RedrivePolicy:
          maxReceiveCount: 2
          deadLetterTargetArn: !GetAtt PageQueueDLQ.Arn

    pullTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: seemyVCSpull
        KeySchema:
          - AttributeName: url
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
          - AttributeName: id
            AttributeType: "N"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 2
    issueTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: seemyVCSissue
        KeySchema:
          - AttributeName: url
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
          - AttributeName: id
            AttributeType: "N"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 2
